// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf3MqinEieA-Jgyg0e15Jc6HWy-4naiNI',
    appId: '1:559078629597:web:37fd5e27867af4d8b13b34',
    messagingSenderId: '559078629597',
    projectId: 'schoolapp-a7a3c',
    authDomain: 'schoolapp-a7a3c.firebaseapp.com',
    storageBucket: 'schoolapp-a7a3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfFd0rmbIq_ETezyjmPf5ebw77jVT6uHI',
    appId: '1:559078629597:android:2ba96bdcc2d30f9ab13b34',
    messagingSenderId: '559078629597',
    projectId: 'schoolapp-a7a3c',
    storageBucket: 'schoolapp-a7a3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBimg8az6MS-WmiDgNPgIAUbYChn4GsjeY',
    appId: '1:559078629597:ios:04dcc39a116120cfb13b34',
    messagingSenderId: '559078629597',
    projectId: 'schoolapp-a7a3c',
    storageBucket: 'schoolapp-a7a3c.appspot.com',
    iosClientId: '559078629597-9vmvnej02g44vbqfv9f8d9jsdl4ookm0.apps.googleusercontent.com',
    iosBundleId: 'menor.com.schoolapp',
  );
}
